CREATE TABLE IF NOT EXISTS public.lesson_resources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id bigint NOT NULL REFERENCES public.lessons(id) ON DELETE CASCADE,
  title text NOT NULL,
  file_name text NOT NULL,
  storage_path text NOT NULL UNIQUE,
  mime_type text,
  file_size bigint,
  uploaded_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS lesson_resources_lesson_id_idx
  ON public.lesson_resources(lesson_id, created_at);

ALTER TABLE public.lesson_resources ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can view lesson resources" ON public.lesson_resources;
CREATE POLICY "Authenticated users can view lesson resources"
  ON public.lesson_resources FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Admins can manage lesson resources" ON public.lesson_resources;
CREATE POLICY "Admins can manage lesson resources"
  ON public.lesson_resources FOR ALL
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.is_admin = true
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid() AND profiles.is_admin = true
  ));

INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('lesson-resources', 'lesson-resources', false, 52428800)
ON CONFLICT (id) DO UPDATE
SET public = false, file_size_limit = 52428800;

DROP POLICY IF EXISTS "Authenticated users can download lesson resources" ON storage.objects;
CREATE POLICY "Authenticated users can download lesson resources"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'lesson-resources');

DROP POLICY IF EXISTS "Admins can upload lesson resources" ON storage.objects;
CREATE POLICY "Admins can upload lesson resources"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'lesson-resources'
    AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = true
    )
  );

DROP POLICY IF EXISTS "Admins can update lesson resources" ON storage.objects;
CREATE POLICY "Admins can update lesson resources"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'lesson-resources'
    AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = true
    )
  );

DROP POLICY IF EXISTS "Admins can delete lesson resources" ON storage.objects;
CREATE POLICY "Admins can delete lesson resources"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'lesson-resources'
    AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = true
    )
  );
