ALTER TABLE public.courses
  ADD COLUMN IF NOT EXISTS requires_enrollment_approval boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.course_enrollment_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id bigint NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  note text,
  reviewed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (course_id, user_id)
);

CREATE INDEX IF NOT EXISTS course_enrollment_requests_status_idx
  ON public.course_enrollment_requests(status, created_at DESC);

ALTER TABLE public.course_enrollment_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Students can view own course requests"
  ON public.course_enrollment_requests FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Students can request course access"
  ON public.course_enrollment_requests FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() AND status = 'pending');

CREATE POLICY "Students can resubmit declined course requests"
  ON public.course_enrollment_requests FOR UPDATE TO authenticated
  USING (user_id = auth.uid() AND status = 'rejected')
  WITH CHECK (user_id = auth.uid() AND status = 'pending');

CREATE POLICY "Course instructors can view requests"
  ON public.course_enrollment_requests FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.courses course
    WHERE course.id = course_id
      AND (course.created_by = auth.uid() OR auth.uid() = ANY(course.instructor_ids))
  ));

DROP POLICY IF EXISTS "enrollments: own insert" ON public.enrollments;
CREATE POLICY "enrollments: own insert"
  ON public.enrollments FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = enrollments.user_id
    AND (
      NOT EXISTS (
        SELECT 1 FROM public.courses course
        WHERE course.id = enrollments.course_id AND course.requires_enrollment_approval = true
      )
      OR EXISTS (
        SELECT 1 FROM public.course_enrollment_requests request
        WHERE request.course_id = enrollments.course_id
          AND request.user_id = auth.uid()
          AND request.status = 'approved'
      )
    )
  );

CREATE OR REPLACE FUNCTION public.review_course_enrollment_request(p_request_id bigint, p_status text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  request_row public.course_enrollment_requests%ROWTYPE;
  course_title text;
BEGIN
  IF p_status NOT IN ('approved', 'rejected') THEN
    RAISE EXCEPTION 'Invalid request status';
  END IF;

  SELECT request.* INTO request_row
  FROM public.course_enrollment_requests request
  WHERE request.id = p_request_id;

  IF request_row.id IS NULL THEN RAISE EXCEPTION 'Enrollment request not found'; END IF;

  SELECT course.title INTO course_title
  FROM public.courses course
  WHERE course.id = request_row.course_id;
  IF NOT EXISTS (
    SELECT 1 FROM public.courses course
    WHERE course.id = request_row.course_id
      AND (course.created_by = auth.uid() OR auth.uid() = ANY(course.instructor_ids))
  ) THEN
    RAISE EXCEPTION 'Only assigned course instructors can review this request';
  END IF;

  UPDATE public.course_enrollment_requests
  SET status = p_status, reviewed_by = auth.uid(), reviewed_at = now(), updated_at = now()
  WHERE id = p_request_id;

  IF p_status = 'approved' THEN
    INSERT INTO public.enrollments(user_id, course_id)
    VALUES (request_row.user_id, request_row.course_id)
    ON CONFLICT DO NOTHING;
  END IF;

  INSERT INTO public.notifications(user_id, type, title, message, link)
  VALUES (
    request_row.user_id,
    CASE WHEN p_status = 'approved' THEN 'course_access_approved' ELSE 'course_access_rejected' END,
    CASE WHEN p_status = 'approved' THEN 'Course access approved' ELSE 'Course access request declined' END,
    CASE WHEN p_status = 'approved'
      THEN 'Your request to join "' || course_title || '" was approved. You can start learning now.'
      ELSE 'Your request to join "' || course_title || '" was not approved.' END,
    CASE WHEN p_status = 'approved' THEN '/my-courses' ELSE '/catalog' END
  );
END;
$$;

REVOKE ALL ON FUNCTION public.review_course_enrollment_request(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.review_course_enrollment_request(bigint, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.notify_course_instructors_of_request()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.notifications(user_id, type, title, message, link)
  SELECT DISTINCT instructor_id, 'course_access_pending', 'Course access request',
         COALESCE(profile.full_name, 'A student') || ' requested access to "' || course.title || '".',
         '/admin'
  FROM public.courses course
  JOIN public.profiles profile ON profile.id = NEW.user_id
  CROSS JOIN LATERAL unnest(
    CASE WHEN cardinality(course.instructor_ids) > 0
      THEN course.instructor_ids
      ELSE ARRAY[course.created_by]::uuid[] END
  ) instructor_id
  WHERE course.id = NEW.course_id AND instructor_id IS NOT NULL;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS course_request_notify_instructors ON public.course_enrollment_requests;
CREATE TRIGGER course_request_notify_instructors
AFTER INSERT OR UPDATE ON public.course_enrollment_requests
FOR EACH ROW
WHEN (NEW.status = 'pending')
EXECUTE FUNCTION public.notify_course_instructors_of_request();

NOTIFY pgrst, 'reload schema';
